name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version: [ '8.17', '8.18', '8.19', '8.20' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'lambda-iu.opam'
          coq_version: ${{ matrix.coq_version }}
